# Generated by Django 4.2.4 on 2023-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=70)),
                ('stuemail', models.EmailField(max_length=254)),
                ('stupass', models.CharField(max_length=70)),
                ('comment', models.CharField(default='not available', max_length=40)),
            ],
        ),
    ]
