# Generated by Django 4.2.4 on 2023-08-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_inheritance', '0002_examcenter_studentcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExamcenter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('model_inheritance.examcenter',),
        ),
    ]
