# Generated by Django 4.2.4 on 2023-08-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_inheritance', '0003_myexamcenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myexamcenter',
            options={'ordering': ['city']},
        ),
    ]
