# Generated by Django 4.2.4 on 2023-09-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_relationship', '0006_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.AddField(
            model_name='page',
            name='id',
            field=models.BigAutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
