# Generated by Django 4.2.4 on 2023-09-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_Gateway', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
